import type { DatabaseOperations } from "@better-ccflare/database";
import { Conflict } from "@better-ccflare/errors";
import { Logger } from "@better-ccflare/logger";
import {
	type ApiKeyGenerationResult,
	type ApiKeyResponse,
	NodeCryptoUtils,
	toApiKeyResponse,
} from "@better-ccflare/types";

const logger = new Logger("ApiKey");

async function mintNewSecret(): Promise<{
	apiKey: string;
	hashedKey: string;
	prefixLast8: string;
}> {
	const crypto = new NodeCryptoUtils();
	const apiKey = await crypto.generateApiKey();
	const hashedKey = await crypto.hashApiKey(apiKey);
	return { apiKey, hashedKey, prefixLast8: apiKey.slice(-8) };
}

/**
 * Generate a new API key
 */
export async function generateApiKey(
	dbOps: DatabaseOperations,
	name: string,
): Promise<ApiKeyGenerationResult> {
	// Validate name
	if (!name || name.trim().length === 0) {
		throw new Error("API key name cannot be empty");
	}

	const trimmedName = name.trim();

	// Validate name length
	if (trimmedName.length > 100) {
		throw new Error("API key name cannot exceed 100 characters");
	}

	// Check if name already exists
	if (await dbOps.apiKeyNameExists(trimmedName)) {
		throw new Error(`API key with name '${trimmedName}' already exists`);
	}

	const { apiKey, hashedKey, prefixLast8 } = await mintNewSecret();

	// Create database record
	const id = globalThis.crypto.randomUUID();
	const now = Date.now();

	await dbOps.createApiKey({
		id,
		name: trimmedName,
		hashedKey,
		prefixLast8,
		createdAt: now,
		isActive: true,
	});

	return {
		id,
		name: trimmedName,
		apiKey,
		prefixLast8,
		createdAt: new Date(now).toISOString(),
	};
}

/**
 * List all API keys
 */
export async function listApiKeys(
	dbOps: DatabaseOperations,
): Promise<ApiKeyResponse[]> {
	const apiKeys = await dbOps.getApiKeys();
	return apiKeys.map(toApiKeyResponse);
}

/**
 * Mint a new plaintext secret for an existing API key, replacing the stored
 * hash and prefix in place. The row's id, name, created_at, usage_count,
 * last_used, and is_active are all preserved.
 */
export async function regenerateApiKey(
	dbOps: DatabaseOperations,
	name: string,
): Promise<ApiKeyGenerationResult> {
	const existing = await dbOps.getApiKeyByName(name);
	if (!existing) {
		throw new Error(`API key '${name}' not found`);
	}

	if (!existing.isActive) {
		throw new Error(
			`API key '${name}' is disabled. Enable it first, or generate a new key.`,
		);
	}

	const { apiKey, hashedKey, prefixLast8 } = await mintNewSecret();

	// Optimistic-concurrency guard: only swap the secret if the row's hash is
	// still the one we read above. If a parallel regenerate already replaced
	// it, this returns 0 and we report 409 — otherwise the racing caller would
	// receive a plaintext that was silently invalidated by the winner.
	const updated = await dbOps.rotateApiKeySecret(
		existing.id,
		existing.hashedKey,
		hashedKey,
		prefixLast8,
	);
	if (!updated) {
		throw Conflict(
			`API key '${name}' was regenerated by another request. Reload and try again.`,
		);
	}

	logger.info(`API key regenerated: name='${existing.name}' id=${existing.id}`);

	return {
		id: existing.id,
		name: existing.name,
		apiKey,
		prefixLast8,
		createdAt: new Date(existing.createdAt).toISOString(),
	};
}

/**
 * Disable an API key (soft delete)
 */
export async function disableApiKey(
	dbOps: DatabaseOperations,
	name: string,
): Promise<boolean> {
	const apiKey = await dbOps.getApiKeyByName(name);
	if (!apiKey) {
		throw new Error(`API key '${name}' not found`);
	}

	if (!apiKey.isActive) {
		throw new Error(`API key '${name}' is already disabled`);
	}

	const success = await dbOps.disableApiKey(apiKey.id);
	if (!success) {
		throw new Error(`Failed to disable API key '${name}'`);
	}

	return true;
}

/**
 * Enable a previously disabled API key
 */
export async function enableApiKey(
	dbOps: DatabaseOperations,
	name: string,
): Promise<boolean> {
	const apiKey = await dbOps.getApiKeyByName(name);
	if (!apiKey) {
		throw new Error(`API key '${name}' not found`);
	}

	if (apiKey.isActive) {
		throw new Error(`API key '${name}' is already active`);
	}

	const success = await dbOps.enableApiKey(apiKey.id);
	if (!success) {
		throw new Error(`Failed to enable API key '${name}'`);
	}

	return true;
}

/**
 * Delete an API key permanently
 */
export async function deleteApiKey(
	dbOps: DatabaseOperations,
	name: string,
): Promise<boolean> {
	const apiKey = await dbOps.getApiKeyByName(name);
	if (!apiKey) {
		throw new Error(`API key '${name}' not found`);
	}

	const success = await dbOps.deleteApiKey(apiKey.id);
	if (!success) {
		throw new Error(`Failed to delete API key '${name}'`);
	}

	return true;
}

/**
 * Get API key statistics
 */
export async function getApiKeyStats(dbOps: DatabaseOperations): Promise<{
	total: number;
	active: number;
	inactive: number;
}> {
	const total = await dbOps.countAllApiKeys();
	const active = await dbOps.countActiveApiKeys();
	const inactive = total - active;

	return {
		total,
		active,
		inactive,
	};
}

/**
 * Format API key for display in CLI
 */
export function formatApiKeyForDisplay(apiKey: ApiKeyResponse): string {
	const status = apiKey.isActive ? "Active" : "Disabled";
	const lastUsed = apiKey.lastUsed
		? new Date(apiKey.lastUsed).toLocaleDateString()
		: "Never";

	return `  ${apiKey.name} (${apiKey.prefixLast8})
    Status: ${status}
    Created: ${new Date(apiKey.createdAt).toLocaleDateString()}
    Last Used: ${lastUsed}
    Usage Count: ${apiKey.usageCount}`;
}

/**
 * Format the result of a regenerate operation for CLI display.
 */
export function formatApiKeyRegenerationResult(
	result: ApiKeyGenerationResult,
): string {
	return formatApiKeyGenerationResult(result).replace(
		"API Key Generated Successfully!",
		"API Key Regenerated Successfully!",
	);
}

/**
 * Format API key generation result for display
 */
export function formatApiKeyGenerationResult(
	result: ApiKeyGenerationResult,
): string {
	return `API Key Generated Successfully!

Name: ${result.name}
Key: ${result.apiKey}  Save this key now - it won't be shown again
Prefix: ${result.prefixLast8}
Created: ${new Date(result.createdAt).toLocaleString()}

Usage:
  Include this key in your requests using the 'x-api-key' header:
  x-api-key: ${result.apiKey}

Example:
  curl -X POST http://localhost:8080/v1/messages \\
    -H "Content-Type: application/json" \\
    -H "x-api-key: ${result.apiKey}" \\
    -d '{"model": "claude-3-haiku-20240307", "messages": [{"role": "user", "content": "Hello"}]}'
`;
}
